### ISSUE TITLE
DroitIO: Recrusive error

### ISSUE THREAD

**Issue by jaybeejs** [jaybeejs/python-droit#8]
When using DroitResourcePackage().io.input(question) you get the following error:
```
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    rawInput = rpack.io.input("Droit> ") # Get input from console
  File ".../droit/io/__init__.py", line 34, in input
    return self.activeModule.input(question)
  File ".../droit/io/console.py", line 17, in input
    inp = input(question)
  [Previous line repeated 997 more times]
RecursionError: maximum recursion depth exceeded
```

**Comment by jaybeejs** [comment]
The error is caused because there is a function called `input` defined and called from itself within the file. The name hast to be changed to e.g. `getinput` so it won't overwrite the standard `input` function.
